[package]
name = "kitsune-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.32.1"
glm = "0.2.3"
glutin = "0.30.3"
image = "0.24.5"
winit = "0.27.5"
